# Generated by Django 3.2 on 2021-04-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courseinfo',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursetitle', models.CharField(max_length=256)),
                ('coursename', models.CharField(max_length=256)),
                ('courseselectioncode', models.IntegerField()),
                ('coursedepartment', models.CharField(default='SOME STRING', max_length=256)),
                ('instructorname', models.CharField(default='SOME STRING', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('courseid', models.IntegerField()),
                ('coursename', models.CharField(max_length=256)),
                ('instructorname', models.CharField(default='SOME STRING', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=256)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
